version: "3.8"

services:
  db:
    image: mysql:8.0.28
    platform: linux/x86_64
    container_name: ledroom-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_HOST: localhost
      MYSQL_PORT: ${DB_PORT_CONTAINER}
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT_PUBLIC}:${DB_PORT_CONTAINER}
