version: "3.8"

services:
  frontend:
    container_name: ledroom-frontend-production
    build:
      context: .
      target: production
      dockerfile: ./frontend/Dockerfile
    env_file:
      - ./env/.env.production
    ports:
      - ${FRONTEND_PORT_PUBLIC}:${FRONTEND_PORT_CONTAINER}

  backend:
    container_name: ledroom-backend-production
    build:
      context: ./backend
      target: production
      dockerfile: Dockerfile
    env_file:
      - ./env/.env.production
    ports:
      - ${BACKEND_PORT_PUBLIC}:${BACKEND_PORT_CONTAINER}
      - ${BACKEND_WS_PORT_PUBLIC}:${BACKEND_WS_PORT_CONTAINER}

  db:
    container_name: ledroom-db-production
    image: mysql:8.0.28
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_HOST: localhost
      MYSQL_PORT: ${DB_PORT_PUBLIC}
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT_PUBLIC}:${DB_PORT_CONTAINER}
