version: "3.8"

services:
  db:
    image: postgres
    platform: linux/x86_64
    container_name: ledroom-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASS_BACKEND}
      POSTGRES_USER: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT_PUBLIC}:5432
